-- 航空貨物ロジステックシステム データベース初期化スクリプト

-- 貨物テーブル
CREATE TABLE CARGO (
    CARGO_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    FLIGHT_NUMBER VARCHAR(10) NOT NULL,
    ORIGIN_AIRPORT VARCHAR(3) NOT NULL,
    DESTINATION_AIRPORT VARCHAR(3) NOT NULL,
    CARGO_TYPE VARCHAR(50) NOT NULL,
    WEIGHT DECIMAL(10,2) NOT NULL,
    VOLUME DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SHIPPER_NAME VARCHAR(100) NOT NULL,
    CONSIGNEE_NAME VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP
);

-- 入荷テーブル
CREATE TABLE INBOUND (
    INBOUND_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CARGO_ID VARCHAR(20) NOT NULL,
    FLIGHT_NUMBER VARCHAR(10) NOT NULL,
    ARRIVAL_DATE DATE NOT NULL,
    ARRIVAL_TIME TIME NOT NULL,
    TERMINAL VARCHAR(10) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ARRIVED',
    HANDLER_ID VARCHAR(20),
    NOTES VARCHAR(1000),
    CREATED_DATE TIMESTAMP,
    FOREIGN KEY (CARGO_ID) REFERENCES CARGO(CARGO_ID)
);

-- 出荷テーブル
CREATE TABLE OUTBOUND (
    OUTBOUND_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CARGO_ID VARCHAR(20) NOT NULL,
    FLIGHT_NUMBER VARCHAR(10) NOT NULL,
    DEPARTURE_DATE DATE NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    TERMINAL VARCHAR(10) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    HANDLER_ID VARCHAR(20),
    NOTES VARCHAR(1000),
    CREATED_DATE TIMESTAMP,
    FOREIGN KEY (CARGO_ID) REFERENCES CARGO(CARGO_ID)
);

-- 追跡テーブル
CREATE TABLE TRACKING (
    TRACKING_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    CARGO_ID VARCHAR(20) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    TIMESTAMP TIMESTAMP,
    HANDLER_ID VARCHAR(20),
    NOTES VARCHAR(1000),
    FOREIGN KEY (CARGO_ID) REFERENCES CARGO(CARGO_ID)
);

-- ハンドラー（作業員）テーブル
CREATE TABLE HANDLER (
    HANDLER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    HANDLER_NAME VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    CONTACT_NUMBER VARCHAR(20),
    EMAIL VARCHAR(100),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_DATE TIMESTAMP
);

-- 空港テーブル
CREATE TABLE AIRPORT (
    AIRPORT_CODE VARCHAR(3) NOT NULL PRIMARY KEY,
    AIRPORT_NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    TIMEZONE VARCHAR(10) NOT NULL
);

-- フライトテーブル
CREATE TABLE FLIGHT (
    FLIGHT_NUMBER VARCHAR(10) NOT NULL PRIMARY KEY,
    ORIGIN_AIRPORT VARCHAR(3) NOT NULL,
    DESTINATION_AIRPORT VARCHAR(3) NOT NULL,
    DEPARTURE_TIME TIME NOT NULL,
    ARRIVAL_TIME TIME NOT NULL,
    AIRCRAFT_TYPE VARCHAR(20),
    STATUS VARCHAR(20) DEFAULT 'SCHEDULED',
    FOREIGN KEY (ORIGIN_AIRPORT) REFERENCES AIRPORT(AIRPORT_CODE),
    FOREIGN KEY (DESTINATION_AIRPORT) REFERENCES AIRPORT(AIRPORT_CODE)
);

-- インデックス作成
CREATE INDEX IDX_CARGO_FLIGHT ON CARGO(FLIGHT_NUMBER);
CREATE INDEX IDX_CARGO_STATUS ON CARGO(STATUS);
CREATE INDEX IDX_INBOUND_DATE ON INBOUND(ARRIVAL_DATE);
CREATE INDEX IDX_OUTBOUND_DATE ON OUTBOUND(DEPARTURE_DATE);
CREATE INDEX IDX_TRACKING_CARGO ON TRACKING(CARGO_ID);
CREATE INDEX IDX_TRACKING_TIMESTAMP ON TRACKING(TIMESTAMP);

-- サンプルデータ挿入
INSERT INTO AIRPORT (AIRPORT_CODE, AIRPORT_NAME, CITY, COUNTRY, TIMEZONE) VALUES
('NRT', 'Narita International Airport', 'Tokyo', 'Japan', 'Asia/Tokyo'),
('HND', 'Haneda Airport', 'Tokyo', 'Japan', 'Asia/Tokyo'),
('LAX', 'Los Angeles International Airport', 'Los Angeles', 'USA', 'America/Los_Angeles'),
('JFK', 'John F. Kennedy International Airport', 'New York', 'USA', 'America/New_York'),
('LHR', 'London Heathrow Airport', 'London', 'UK', 'Europe/London'),
('CDG', 'Charles de Gaulle Airport', 'Paris', 'France', 'Europe/Paris');

INSERT INTO HANDLER (HANDLER_ID, HANDLER_NAME, DEPARTMENT, CONTACT_NUMBER, EMAIL) VALUES
('H001', '田中太郎', '入荷部門', '090-1234-5678', 'tanaka@aircargo.com'),
('H002', '佐藤花子', '出荷部門', '090-2345-6789', 'sato@aircargo.com'),
('H003', '鈴木一郎', '追跡部門', '090-3456-7890', 'suzuki@aircargo.com');

INSERT INTO FLIGHT (FLIGHT_NUMBER, ORIGIN_AIRPORT, DESTINATION_AIRPORT, DEPARTURE_TIME, ARRIVAL_TIME, AIRCRAFT_TYPE) VALUES
('NH001', 'NRT', 'LAX', '10:00:00', '06:00:00', 'Boeing 787'),
('NH002', 'LAX', 'NRT', '14:00:00', '18:00:00', 'Boeing 787'),
('JL001', 'HND', 'JFK', '11:00:00', '14:00:00', 'Boeing 777'),
('JL002', 'JFK', 'HND', '16:00:00', '20:00:00', 'Boeing 777'); 