version: '3.8'

services:
  db2:
    image: ibmcom/db2:11.5.7.0
    container_name: air-cargo-db2
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DB2_DEV=true
      - DB2ENABLE_CDC=true
      - DBNAME=AIRCARGO
      - PERSISTENT_HOME=true
      - ENABLE_ORACLE_COMPATIBILITY=false
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database
      - ./database/init:/var/custom/init
    command: bash -c "if [ ! -f /database/.initialized ]; then /var/db2_setup/lib/setup_db2.sh && touch /database/.initialized; fi && /var/db2_setup/lib/start_db2.sh"
    # healthcheck:
    #   test: ["CMD", "db2", "connect", "to", "AIRCARGO", "user", "db2inst1", "using", "password"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 300s

  backend:
    image: docker-db2-backend:latest
    container_name: air-cargo-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:db2://db2:50000/AIRCARGO
      - SPRING_DATASOURCE_USERNAME=db2inst1
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.ibm.db2.jcc.DB2Driver
      - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - "8080:8080"
    depends_on:
      - db2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    image: docker-db2-frontend:latest
    container_name: air-cargo-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  db2_data: 