SELECT
    CARGO_ID,
    FLIGHT_NUMBER,
    ORIGIN_AIRPORT,
    DESTINATION_AIRPORT,
    CARGO_TYPE,
    WEIGHT,
    VOLUME,
    STATUS,
    SHIPPER_NAME,
    CONSIGNEE_NAME,
    CREATED_DATE,
    UPDATED_DATE,
    VERSION
FROM CARGO
WHERE STATUS = /* status */''
ORDER BY CREATED_DATE DESC 