SELECT
    TRACKING_ID,
    CARGO_ID,
    LOCATION,
    STATUS,
    TIMESTAMP,
    HANDLER_ID,
    NOTES,
    VERSION
FROM TRACKING
WHERE TIMESTAMP BETWEEN /* start */'' AND /* end */''
ORDER BY TIMESTAMP DESC 