SELECT
    OUTBOUND_ID,
    CARGO_ID,
    FLIGHT_NUMBER,
    DEPARTURE_DATE,
    DEPARTURE_TIME,
    TERMINAL,
    STATUS,
    HANDLER_ID,
    NOTES,
    CREATED_DATE,
    VERSION
FROM OUTBOUND
ORDER BY CREATED_DATE DESC 