spring:
  application:
    name: air-cargo-logistics
  
  profiles:
    active: docker
  
  datasource:
    url: jdbc:db2://${DB2_HOST:localhost}:${DB2_PORT:50000}/${DB2_DATABASE:AIRCARGO}
    username: ${DB2_USER:db2inst1}
    password: ${DB2_PASSWORD:db2inst1}
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.DB2Dialect
    
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.aircargo: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 