SELECT
    INBOUND_ID,
    CARGO_ID,
    FLIGHT_NUMBER,
    ARRIVAL_DATE,
    ARRIVAL_TIME,
    TERMINAL,
    STATUS,
    HANDLER_ID,
    NOTES,
    CREATED_DATE,
    VERSION
FROM INBOUND
WHERE CARGO_ID = /* cargoId */''
ORDER BY CREATED_DATE DESC 